### ISSUE TITLE
hook function error in component preview open

### ISSUE THREAD

**Issue by arifnpm** [webcodesk/webcodesk-srv#11]
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app

**Comment by ipselon** [comment]
Would you mind to post the source code of your component?

**Comment by ipselon** [comment]
@arifnpm could you add the source code to the issue?

**Comment by ipselon** [comment]
I'm closing this issue due to the unresponsive issue creator.
