### ISSUE TITLE
How does this compare to Webflow?

### ISSUE THREAD

**Issue by GrayStrider** [webcodesk/webcodesk-srv#13]
Feature-wise

**Comment by ipselon** [comment]
@GrayStrider, Webflow is an online design/builder for static sites. Webcodesk is a development tool for React Web Applications. Webcodesk works with the local source code. Webcodesk online version is only for demonstration purposes.

So, I can say they are absolutely different tools.

**Comment by ipselon** [comment]
I'm closing this issue. Let's discuss issues not related to bugs at the forum:  https://www.reddit.com/r/webcodesk/
