### ISSUE TITLE
Renaming of Pages, Flows maybe also Templates

### ISSUE THREAD

**Issue by HeikoMarkgraf** [webcodesk/webcodesk-srv#24]
Hi,

I missing a way to rename flows, pages and maybe also templates (didn't worked with templates yet).

Specially Flows are non connected and should be easily to be renamed. 
On pages this could destroy routing, of course, you have to be careful with that.
On templates this might make problems with Pages created out of the template? Maybe all usages could be auto updated?

**Comment by ipselon** [comment]
Hi,

> I missing a way to rename flows, pages and maybe also templates

There is no renaming option so far. However, you can copy and then delete options as a workaround.

>  On templates this might make problems with Pages created out of the template?

Nope, there should not be any problem with renaming templates. Only instance names are important.

> Maybe all usages could be auto updated?

I'm not sure this is a good idea. I do not like touching the user's source code.

**Comment by SoftHai** [comment]
Hi,
thanks for your answers.
Would be nice to get renaming support in the future.

**Comment by ipselon** [comment]
Implemented in https://github.com/webcodesk/webcodesk-srv/releases/tag/v2.0.3
