### ISSUE TITLE
Manipulating props in funcs of an unset control

### ISSUE THREAD

**Issue by SoftHai** [webcodesk/webcodesk-srv#26]
Hi,
while continue working with your tool I had to tackle the following issue:

- I added a data receiving control to the page (like a list of items)
- I didn't change any of the props (leave to default) because they was fine
- I wrote a function which should use the current `stateOptions.props` and update it with the new received data (e.g. a list of objects) from the function input.
- I wrote this updated props to the dispatch function.

While doing this I saw 2 strange behaviors:
1. The control didn't received the new data. By debugging the tool for a while, 
![Bug Report - Webcodesk](https://user-images.githubusercontent.com/5662304/78604165-aaba9b00-7859-11ea-9b10-eafe4599d769.png)
I figured out that it uses internally a state cache where all props of all controls are stored. How ever, only the props of controls where the user made changes in the page. If the control was added to the page without any change to the properties, the state of this control was `undefined`. Mean an undefined prop-object was insert into the `*.funcs` and as a result the dispatch function was never called. The flow end at this point.
I'm not sure if this is expected by design. I would expect to get a props-object with the defaults defined in the source code `defaultProps` instead of an undefined one.
2. The flow was a chain of 4 elements. In the flow record it shows that the chain stopped at the 2nd element. But in real the chain stopped at the 3rd element. Which leads me to analyzing the wrong function for a while. So it looks for me that when a flow element is executed and never calls the dispatch function, that this element is not recorded as executed flow-element in the record.

**Comment by ipselon** [comment]
@SoftHai,

Recently I fixed a bug in react-app-framework where components did not get default property values if the component instance did not trigger any event. 

The bug was fixed in version 2.0.28 of react-app-framework.

If the new version of the framework doesn't fix your bug, I ask you to show me the code where unclear behavior happens.

**Comment by SoftHai** [comment]
Hi,

okay. Can I update the react-app-framework without updating the Webcodesk application without any issue?

**Comment by ipselon** [comment]
Yes, just remove the old one, and then install new Framework lib.
```
> yarn remove react-app-framework

> yarn add react-app-framework -D -E
```

**Comment by ipselon** [comment]
Hi @SoftHai,

Did the library update help solve your problem?

**Comment by ipselon** [comment]
I'm closing this issue since it seems there is a solution:  https://github.com/webcodesk/webcodesk-srv/issues/26#issuecomment-610188457
