### ISSUE TITLE
Error in plugin 'gulp-babel' while running yarn run build-server

### ISSUE THREAD

**Issue by couaky** [webcodesk/webcodesk-srv#5]
Hi !
I got this error while trying to build the project:
```
>yarn --version
1.22.0
```

```
>yarn run build-server
yarn run v1.22.0
$ gulp --gulpfile ./gulpfile.js build
[11:46:42] Using gulpfile ~/work/webcodesk-srv/gulpfile.js
[11:46:42] Starting 'build'...
[11:46:42] Starting 'clean'...
[11:46:42] Finished 'clean' after 5.87 ms
[11:46:42] Starting 'commons'...
[11:46:43] 'commons' errored after 964 ms
[11:46:43] Error in plugin "gulp-babel"
Message:
    The number of constructor arguments in the derived class t must be >= than the number of constructor arguments of its base class.
[11:46:43] 'build' errored after 971 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

did you already face this problem ?

Thanks.

**Comment by couaky** [comment]
Issue seems to come from gulp-javascript-obfuscator plugin.
See: https://github.com/javascript-obfuscator/gulp-javascript-obfuscator/issues/28.

I'm using node v13.8.0

**Comment by couaky** [comment]
I fixed the issue by forcing an update of javascript-obfuscator which is a dependency of gulp-javascript-obfuscator.
I did not find the yarn command to do that (yarn upgrade just update the first level dependencies). So I performed a remove followed by an add command.

```
yarn remove gulp-javascript-obfuscator
yarn add --dev gulp-javascript-obfuscator
```

**Comment by ipselon** [comment]
I'm closing this since it is resolved.
